name = "buildkit-preview"
main = "src/index.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "buildkitlabs.com/preview/*", zone_id = "51c3ed05461f7df53bd31ac05038ac9a" }
]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "buildkit-files"
